- hosts: localhost
  become: true
  tasks:
  - name: Install prerequisites
    apt:  name={{item}} update_cache=yes
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
  - name: Add Dockerr's official GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker APT repo
    apt_repository:
     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  - name: Install docker
    apt: 
     name: docker-ce
     state: present
  - name: Enable container logging to syslog
    copy:
     src: 'daemon.json'
     dest: '/etc/docker/daemon.json'
